language: node_js
node_js: 0.1
deploy:
  provider: heroku
  api_key:
    secure: Ri3qVP11BnZRDwj5OvAoRZP2bXVFf281bAC6wzMITBz4FUfroxZ33SvHostIGssnk5L9TPpLb+4rsTHImneqM+7VW/bx8r3433VMbYBp/GdezjHYYIAQX7oBnZDnJx2DAsUM2ajt2oC6Ggi9lp66qsaCyc9VO41abMVD9ID7dD8=
  app: lit-earth-8658
